name: e2e_interop_test
description: End-to-end test for node interop and builders
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  node_interop:
    path: ../node_interop

dev_dependencies:
  test: ^1.15.7
  build_runner: 1.11.1
  build_node_compilers:
    git:
      url: git://github.com/Semapl3/node-interop
      path: build_node_compilers