name: build_node_compilers
version: 0.3.1
description: Builders wrapping DDC and dart2js compilers configured to output Node modules.
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  analyzer: ^1.1.0
  bazel_worker: ^0.1.25
  collection: ^1.15.0
  crypto: ^3.0.0
  build_modules: ^3.0.5
  meta: ^1.3.0
  build: ^1.6.3
  build_config: ^0.4.6
  logging: ^1.0.0
  node_preamble: ^1.4.13
  path: ^1.8.0
  pool: ^1.5.0
  scratch_space: ^0.0.4+3

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
  build_test: ^1.3.7
  a:
    path: test/fixtures/a
  b:
    path: test/fixtures/b
