name: build_node_compilers
version: 0.3.1
description: Builders wrapping DDC and dart2js compilers configured to output Node modules.
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  analyzer: ^0.41.2
  bazel_worker: ^0.1.25
  collection: 1.14.13
  crypto: ^2.1.5
  build_modules: ^3.0.2
  meta: 1.2.3
  build: ^1.6.0
  build_config: ^0.4.5
  logging: ^0.11.4
  node_preamble: ^1.4.13
  path: 1.6.4
  pool: ^1.4.0
  scratch_space: ^0.0.4+3

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.15.7
  build_test: ^1.3.6
  a:
    path: test/fixtures/a
  b:
    path: test/fixtures/b
