name: node_io
description: Like dart:io but with Node.js.
version: 1.2.0
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
publish_to: none

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  file: ^6.1.0
  node_interop:
    path: ../node_interop
  path: ^1.8.0

dev_dependencies:
  js: ^0.6.3
  pedantic: ^1.11.0
  test: ^1.16.5
  build_runner: 1.11.5
  build_node_compilers:
    path: ../build_node_compilers
  build_test: ^1.3.7