name: node_io
description: Like dart:io but with Node.js.
version: 1.2.0
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
publish_to: none

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  file: ^5.2.1
  node_interop:
    git:
      url: git://github.com/Semapl3/node-interop
      path: node_interop
  path: 1.6.4

dev_dependencies:
  js: ^0.6.2
  pedantic: 1.9.2
  build_runner: 1.11.1
  test: ^1.15.7
  build_test: ^1.3.6
  build_node_compilers:
    git:
      url: git://github.com/Semapl3/node-interop
      path: build_node_compilers